# Generated by Django 5.0.2 on 2024-02-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('direccion_envio', models.TextField()),
                ('fecha_pedido', models.DateField()),
                ('estado_pedido', models.CharField(max_length=50)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=255)),
                ('nombre_contacto', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('numero_telefonico', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
