# Generated by Django 5.0.2 on 2024-03-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigVentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
